import os

# Storage initializer downloads the model from Model Storage to /mnt/models
# On a remote host MODEL_DIR is /mnt/models
MODEL_DIR = os.getenv("MODEL_DIR", ".")

# MODEL_URI is generated by aiXplain's model store.
MODEL_URI = os.getenv("MODEL_URI", "model")

class ModelResolver():
    def __init__(self) -> None:
        self._model_uri = MODEL_URI

    @staticmethod
    def resolve_path():
        model_path = os.path.join(MODEL_DIR, MODEL_URI)
        return model_path

    @staticmethod
    def model_uri():
        return MODEL_URI